### ISSUE TITLE
`ls` takes a long time with buckets with lots of files

### ISSUE THREAD

**Issue by bmabey** [dask/gcsfs#24] opened 2017-10-31 20:39 UTC
I have a bucket with several directories, each of which has thousands of files. When querying one of the directories that has 3600 files a call to `fs.ls("bucket/my-dir")` takes several minutes. I actually don't know how long it takes since I've never let it finish. In contrast, the google client takes 3.4 seconds to return the directory listing `[f for f in bucket.list_blobs(prefix='my-dir')]` (the comprehension is to force iteration over the iterator object they return).

**Comment by martindurant** [comment] 2017-10-31 21:46
Indeed, gcsfs has not yet implemented file listing with prefix/delimiter in the way that s3fs has. The method used there could be copied (they should be very similar), but of course this takes some effort.
#22 might be of interest to you: it enables you to get info and open files for reading when you already know the specific path and don't need to list the bucket.

**Comment by bmabey** [comment] 2017-10-31 23:01
Okay, taking a look at the implementation we would need to switch out the use of `list_bucket` to use this endpoint instead: https://cloud.google.com/storage/docs/json_api/v1/objects/list

Is that what you were thinking?

**Comment by martindurant** [comment] 2017-11-01 02:43
Yes, I think that's it. It would require changing what we store in the cache.

**Comment by martindurant** [comment] 2017-11-03 15:50
Similar, but not duplicate of #21

**Comment by asford** [comment] 2018-02-26 04:21
Resolved with #57.

**Closed by asford** 2018-02-26 04:21 UTC
