### ISSUE TITLE
Bug: find/ls/expand_path do not work as expected

### ISSUE THREAD

**Issue by pvanderlinden** [dask/gcsfs#357] opened 2021-03-08 17:29 UTC
I first created the structure:
```
fs.touch('bucket/testcase/df/_SUCCESS')
fs.touch('bucket/testcase/df/')
fs.touch('bucket/testcase/df/sub/file')
```

Now I started a new python process (not entirely sure if this is needed):

```
>>> fs.ls('bucket/testcase/df/')
['bucket/testcase/df/',
 'bucket/testcase/df/_SUCCESS',
 'bucket/testcase/df/sub']
>>> fs.find('bucket/testcase/df/')
['bucket/testcase/df/',
 'bucket/testcase/df/_SUCCESS',
 'bucket/testcase/df/sub/file']
>>> fs.ls('bucket/testcase/df/')
['bucket/testcase/df/_SUCCESS']
>>>  fs.expand_path('bucket/testcase/df/', recursive=True)
['bucket/testcase',
 'bucket/testcase/df',
 'bucket/testcase/df/',
 'bucket/testcase/df/_SUCCESS',
 'bucket/testcase/df/sub',
 'bucket/testcase/df/sub/file']

```

**Comment by pvanderlinden** [comment] 2021-03-08 17:31
As mentioned here: https://github.com/dask/gcsfs/pull/355
This is probably related to the code injecting the directories in `fs`, but mainly on how `_parent` works. `_parent` is used mainly for caching purposes.

**Comment by brl0** [comment] 2021-03-08 17:58
I think this may be a duplicate of #354, which was just fixed in #355.
I just tested with the `main` branch and these cases seem to work as expected.
`fs.find` has a parameter `withdirs` to control whether it returns directories.  Surprisingly, it even works correctly when the file is named `/` as in your example above, which I wouldn't have expected to be an allowed file name.
Hope this helps.

**Comment by martindurant** [comment] 2021-03-08 18:00
Thanks for testing, @brl0

**Closed by martindurant** 2021-03-08 18:00 UTC

**Comment by pvanderlinden** [comment] 2021-03-09 16:40
Thanks, Didn't realize that PR was fixing this issue as well.

**Comment by martindurant** [comment] 2021-03-09 16:41
I think `find` with a path ending with "/" is still broken. See https://github.com/intake/filesystem_spec/issues/562
